### ISSUE TITLE
dangerous assertion?

### ISSUE THREAD

**Issue by hematthi** [RvSpectML/EchelleCCFs.jl#53]
https://github.com/RvSpectML/EchelleCCFs.jl/blob/a639217e24ebc59282d42e27d739d3aea1a032c6/src/ccf/calc_ccf.jl#L31

Isn't this dangerous if `issorted( plan.line_list.λ )` is false but `assume_sorted=true`? I imagine you'd want to be sure that `plan.line_list.λ` is sorted

**Comment by hematthi** [comment]
https://github.com/RvSpectML/EchelleCCFs.jl/blob/a639217e24ebc59282d42e27d739d3aea1a032c6/src/ccf/calc_ccf.jl#L77

**Comment by hematthi** [comment]
https://github.com/RvSpectML/EchelleCCFs.jl/blob/a639217e24ebc59282d42e27d739d3aea1a032c6/src/ccf/calc_ccf.jl#L131

**Comment by eford** [comment]
`assume_sorted` is an optimization flag.  Yes, it's dangerous to say true when it's not.
