### ISSUE TITLE
check if `calc_length_ccf_v_grid` is doing what is intended (see Issue #52)

### ISSUE THREAD

**Issue by hematthi** [RvSpectML/EchelleCCFs.jl#56]
https://github.com/RvSpectML/EchelleCCFs.jl/blob/a639217e24ebc59282d42e27d739d3aea1a032c6/src/ccf/plan.jl#L51-L57

**Comment by hematthi** [comment]
See #52

**Comment by eford** [comment]
Fixed with #52
