### ISSUE TITLE
if intended to index `x` in steps of 2i, should check that `length(ifo.x) = 2*length(info.gw)`?

### ISSUE THREAD

**Issue by hematthi** [RvSpectML/EchelleCCFs.jl#88]
https://github.com/RvSpectML/EchelleCCFs.jl/blob/a639217e24ebc59282d42e27d739d3aea1a032c6/src/mask_shapes/integrate.jl#L34-L37

**Comment by eford** [comment]
Ok, since enforced in constructor.
