### ISSUE TITLE
check if `n1` = 0/1 for even/odd or vice versa

### ISSUE THREAD

**Issue by hematthi** [RvSpectML/EchelleCCFs.jl#89]
https://github.com/RvSpectML/EchelleCCFs.jl/blob/a639217e24ebc59282d42e27d739d3aea1a032c6/src/mask_shapes/integrate.jl#L30
https://github.com/RvSpectML/EchelleCCFs.jl/blob/a639217e24ebc59282d42e27d739d3aea1a032c6/src/mask_shapes/integrate.jl#L38

**Comment by hematthi** [comment]
This function uses the opposite if/else on `n1`?
https://github.com/RvSpectML/EchelleCCFs.jl/blob/a639217e24ebc59282d42e27d739d3aea1a032c6/src/mask_shapes/integrate.jl#L46-L67

**Comment by eford** [comment]
This looks ok to me, since line 7 says
`x::SVector{Order,RetT}  # Technically, order = Order-1`
